// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmtqpdzucjcqxeapunig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtdHFwZHp1Y2pjcXhlYXB1bmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjgyNzcsImV4cCI6MjA2MDc0NDI3N30.kQGfHxmMeBovoINw655gl9jq1BC7iwB6TpUvgBrmjrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);